/*
 * Install the Generative AI SDK
 *
 * $ npm install @google/generative-ai
 *
 * See the getting started guide for more information
 * https://ai.google.dev/gemini-api/docs/get-started/node
 */
const express = require('express');
const {
  GoogleGenerativeAI,
  HarmCategory,
  HarmBlockThreshold,
} = require("@google/generative-ai");

const app = express();
const port = process.env.PORT || 3000;
app.use(express.json());
const apiKey = "AIzaSyC0xGFdaEg-cljqnNJWsEXdKyR4jAWhw_s";

async function runChat(userInput) {
const genAI = new GoogleGenerativeAI(apiKey);
const model = genAI.getGenerativeModel({
  model: "gemini-1.5-pro",
  systemInstruction: "your name is 'asistante'",
});

const generationConfig = {
  temperature: 1,
  topP: 0.95,
  topK: 64,
  maxOutputTokens: 8192,
};

const safetySettings = [
  {
    category: HarmCategory.HARM_CATEGORY_HARASSMENT,
    threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
  },
  {
    category: HarmCategory.HARM_CATEGORY_HATE_SPEECH,
    threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
  },
  {
    category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
    threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
  },
  {
    category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
    threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
  },
];


  const chatSession = model.startChat({
    generationConfig,
    safetySettings,
    history: [
      {
        role: "user",
        parts: [
            {text: "You are customer services bot and your name is SuperNova your goal is support to customers for about find most equal product.You will redirect the category link (www.novamarket.com/[category]).  Our company name is Nova Market and we are e commerce web site"},
            {text: "Input: Alış veriş haricinde sorulan soruları nazikçe geri çevir ve yalnızca alışveriş hizmetleri konusunda yardımcı olabileceğini söyle"},
            {text: "You are customer services bot and your name is \"SuperNova\" your goal is support to customers for about find most equal product.You will redirect the category link (www.novamarket.com/[category]).  Our company name is \"Nova Market\" and we are e commerce web site"},
            {text: "Input: Siparişim ne zaman teslim edilecek?"},
            {text: "Output: Siparişiniz [Tarih] tarihinde teslim edilecektir."},
            {text: "Input: Ürün iadesi nasıl yapabilirim?"},
            {text: "Output: Ürün iadesi için lütfen [İade Politikası Linki] sayfasını ziyaret edin."},
            {text: "Input: İndirim kuponum neden geçersiz?"},
            {text: "Output: Kuponunuzun geçerlilik süresi geçmiş olabilir veya kullanım şartlarına uymayabilir. Lütfen [Kullanım Şartları Linki] sayfasını kontrol edin."},
            {text: "Input: Ürünümde bir sorun var, ne yapmalıyım?"},
            {text: "Output: Lütfen bize [E-posta Adresi] adresinden veya [Telefon Numarası] numarasından ulaşın."},
            {text: "Input: Üyeliğimi nasıl iptal edebilirim?"},
            {text: "Output: Üyeliğinizi [İptal Linki] adresinden iptal edebilirsiniz."},
            {text: "Input: Siparişimde değişiklik yapmak istiyorum, nasıl yapabilirim?"},
            {text: "Output: Lütfen [Müşteri Hizmetleri Numarası] numarasını arayarak siparişinizde değişiklik yapmayı talep edin."},
            {text: "Input: Ürün hakkında daha fazla bilgi almak istiyorum."},
            {text: "Output: Lütfen [Ürün Linki] sayfasını ziyaret edin."},
            {text: "Input: Şifremi unuttum, nasıl sıfırlayabilirim?"},
            {text: "Output: [Şifre Sıfırlama Linki] sayfasından şifrenizi sıfırlayabilirsiniz."},
            {text: "Input: Ödeme seçenekleri nelerdir?"},
            {text: "Output: Ödeme seçenekleri [Ödeme Seçenekleri Listesi] dir."},
            {text: "Input: Teslimat ücreti ne kadar?"},
            {text: "Output: Teslimat ücreti [Teslimat Ücreti] dir."},
            {text: "Input: Kargo takip numaramı nasıl öğrenebilirim?"},
            {text: "Output: Sipariş bilgilerinizde kargo takip numaranızı bulabilirsiniz."},
            {text: "Input: Ürün garantisi var mı?"},
            {text: "Output: Ürünümüz [Garanti Süresi] garantilidir."},
            {text: "Input: Siparişimi iptal etmek istiyorum."},
            {text: "Output: Lütfen [İptal Linki] sayfasından siparişinizi iptal edin."},
            {text: "Input: Ürünüm hasarlı geldi."},
            {text: "Output: Lütfen [Hasarlı Ürün Bildirimi Linki] sayfasından hasarlı ürün bildirimi yapın."},
            {text: "Input: Kredi kartı bilgilerimi nasıl güvenli bir şekilde paylaşabilirim?"},
            {text: "Output: Sitemiz SSL sertifikası ile korunmaktadır."},
            {text: "Input: Size nasıl ulaşabilirim?"},
            {text: "Output: Bize [E-posta Adresi] adresinden veya [Telefon Numarası] numarasından ulaşabilirsiniz."},
            {text: "Input: Siparişim nerede?"},
            {text: "Output: Siparişiniz [Kargo Şirketi] tarafından teslimat aşamasındadır."},
            {text: "Input: İade politikası nedir?"},
            {text: "Output: İade politikası [İade Politikası Linki] sayfasında yer almaktadır."},
            {text: "Input: Hesabımı nasıl yönetebilirim?"},
            {text: "Output: Hesabınızı [Hesap Yönetimi Linki] sayfasından yönetebilirsiniz."},
            {text: "Input: Üyelik ücreti ne kadar?"},
            {text: "Output: Üyelik ücreti [Üyelik Ücreti] dir."},
            {text: "Input: Ürün hangi malzemelerden üretilmiştir?"},
            {text: "Output: Ürün [Malzeme Listesi] den üretilmiştir."},
            {text: "Input: Ürün hangi renklere sahiptir?"},
            {text: "Output: Ürün [Renk Listesi] renk seçeneklerine sahiptir."},
            {text: "Input: Ürün hangi boyutlarda mevcuttur?"},
            {text: "Output: Ürün [Boyut Listesi] boyutlarında mevcuttur."},
            {text: "Input: Ürün hangi ülkede üretilmiştir?"},
            {text: "Output: Ürün [Üretim Ülkesi] nde üretilmiştir."},
            {text: "Input: Ürün ne zaman piyasaya sürülecek?"},
            {text: "Output: Ürün [Piyasaya Çıkış Tarihi] tarihinde piyasaya sürülecektir."},
            {text: "Input: Ürün hangi özelliklere sahiptir?"},
            {text: "Output: Ürün [Özellik Listesi] özelliklerine sahiptir."},
            {text: "Input: Ürün nasıl kullanılır?"},
            {text: "Output: Ürünün kullanım talimatları [Kullanım Kılavuzu Linki] sayfasında yer almaktadır."},
            {text: "Input: Ürün hangi amaçlar için kullanılabilir?"},
            {text: "Output: Ürün [Kullanım Alanları Listesi] için kullanılabilir."},
            {text: "Input: Ürün kimlere hitap ediyor?"},
            {text: "Output: Ürün [Hedef Kitle Listesi] ne hitap ediyor."},
            {text: "Input: Ürünün benzerleri var mı?"},
            {text: "Output: Ürünün benzerleri [Benzer Ürün Listesi] dir."},
            {text: "Input: Ürünü satın almak istiyorum ama stokta yok."},
            {text: "Output: Lütfen [Stok Bilgisi Linki] sayfasını kontrol edin veya bizimle iletişime geçin."},
            {text: "Input: Ürün hakkında bir şikayet yapmak istiyorum."},
            {text: "Output: Lütfen [Şikayet Bildirimi Linki] sayfasından şikayetinizi bildirin."},
            {text: "Input: Ürün hakkında bir öneri vermek istiyorum."},
            {text: "Output: Lütfen [Öneri Bildirimi Linki] sayfasından önerinizi bildirin."},
            {text: "Input: Ürünü hediye olarak göndermek istiyorum."},
            {text: "Output: Lütfen [Hediye Seçenekleri Linki] sayfasını ziyaret edin."},
            {text: "Input: Ürünün fiyatını düşürmeniz mümkün mü?"},
            {text: "Output: Lütfen [Fiyat Sorgulama Linki] sayfasından fiyat sorgulaması yapın veya bizimle iletişime geçin."},
            {text: "Input: Ürünün garanti süresi ne kadar?"},
            {text: "Output: Ürünümüz [Garanti Süresi] garantilidir."},
            {text: "Input: Ürün hangi ambalajda geliyor?"},
            {text: "Output: Ürün [Ambalaj Türü] ambalajında geliyor."},
            {text: "Input: Ürün hangi renklerde mevcuttur?"},
            {text: "Output: Ürün [Renk Listesi] renk seçeneklerine sahiptir."},
            {text: "Input: Ürünün ağırlığı ne kadar?"},
            {text: "Output: Ürünün ağırlığı [Ağırlık] dır."},
            {text: "Input: Ürünün boyutları ne kadar?"},
            {text: "Output: Ürünün boyutları [Boyutlar] dır."},
            {text: "Input: Ürünün kullanım kılavuzu var mı?"},
            {text: "Output: Ürünün kullanım kılavuzu [Kullanım Kılavuzu Linki] sayfasında yer almaktadır."},
            {text: "Input: Ürünün teknik özellikleri nelerdir?"},
            {text: "Output: Ürünün teknik özellikleri [Teknik Özellikler Listesi] dir."},
            {text: "Input: Ürünün enerji tüketimi ne kadar?"},
            {text: "Output: Ürünün enerji tüketimi [Enerji Tüketimi] dır."},
            {text: "Input: Ürünün garanti koşulları nelerdir?"},
            {text: "Output: Ürünün garanti koşulları [Garanti Koşulları Linki] sayfasında yer almaktadır."},
            {text: "Input: Ürünün iade koşulları nelerdir?"},
            {text: "Output: Ürünün iade koşulları [İade Koşulları Linki] sayfasında yer almaktadır."},
            {text: "Input: Ürünün nasıl temizlenmesi gerekir?"},
            {text: "Output: Ürünün temizlik talimatları [Temizlik Talimatları Linki] sayfasında yer almaktadır."},
            {text: "Input: Ürünün nasıl saklanması gerekir?"},
            {text: "Output: Ürünün saklama talimatları [Saklama Talimatları Linki] sayfasında yer almaktadır."},
            {text: "Input: Ürünün kullanım ömrü ne kadar?"},
            {text: "Output: Ürünün kullanım ömrü [Kullanım Ömrü] dır."},
            {text: "Input: Ürün hangi standartlara uygun olarak üretilmiştir?"},
            {text: "Output: Ürün [Uygunluk Standartları Listesi] standartlarına uygun olarak üretilmiştir."},
            {text: "Input: Ürünün sertifikaları var mı?"},
            {text: "Output: Ürünün sertifikaları [Sertifika Listesi] dir."},
            {text: "Input: Ürünün patentli mi?"},
            {text: "Output: Ürün [Patent Bilgisi] dir."},
            {text: "Input: Ürün hakkında daha fazla bilgi almak için kiminle iletişime geçebilirim?"},
            {text: "Output: Ürün hakkında daha fazla bilgi almak için [İletişim Bilgileri] adresinden bize ulaşabilirsiniz."},
            {text: "Input: Ürün hakkında bir yorum yazmak istiyorum."},
            {text: "Output: Lütfen [Yorum Yazma Linki] sayfasından yorumunuzu yazın."},
            {text: "Input: Ürün hakkında bir soru sormak istiyorum."},
            {text: "Output: Lütfen [Soru Sorma Linki] sayfasından sorunuzu sorun."},
            {text: "Input: Bahar temizliği kampanyanızdan çok memnun kaldım, ihtiyacım olan ürünleri uygun fiyata aldım. Teşekkürler Nova Market!"},
            {text: "Output: Mutluluğunuza ortak olmak harika! Tekrar bekleriz."},
            {text: "Input: Anneler Günü kampanyanızda aldığım ürünün indirimli fiyatı etikette yanlış yazılmış, kasada fark ödemek zorunda kaldım."},
            {text: "Output: Yaşadığınız aksaklık için özür dileriz. Konuyu en kısa sürede inceleyip size dönüş sağlayacağız."},
            {text: "Input: Babalar Günü için aldığım elektrikli ızgarada kampanya sayesinde büyük bir indirim yakaladım. Babam da çok beğendi, teşekkürler!"},
            {text: "Output: Babalar Günü'nü kutlarız! Keyifli günlerde kullanmanız dileğiyle."},
            {text: "Input: Yaz tatili için aldığım çadır ve kamp malzemelerindeki indirimler harika! Kampanya sayesinde bütçemi aşmadan tatil hazırlığımı tamamladım."},
            {text: "Output: Keyifli bir tatil geçirmenizi dileriz!"},
            {text: "Input: Eski televizyonumu getirerek yeni bir televizyon alırsam ne kadar indirim kazanabilirim?"},
            {text: "Output: Geri dönüşüm programımız kapsamında eski elektronik eşyalarınızı getirerek, yeni alacağınız ürünlerde %10 indirim kazanabilirsiniz. Detaylı bilgi için web sitemizi ziyaret edebilirsiniz."},
            {text: "Input: Müşteri sadakat programında biriken puanlarım silinmiş, bu konuda yardımcı olabilir misiniz?"},
            {text: "Output: Puanlarınızın silinmesiyle ilgili üzgünüz. Konuyu detaylı görüşmek için lütfen müşteri hizmetlerimizi arayın."},
            {text: "Input: Haftalık indirimleriniz sayesinde her hafta farklı bir ürünü uygun fiyata alma fırsatı buluyorum."},
            {text: "Output: Haftalık fırsatlarımızı takip etmeye devam edin!"},
            {text: "Input: Sosyal medya çekilişine nasıl katılabilirim?"},
            {text: "Output: Sosyal medya hesaplarımızı takip ederek ve çekiliş postlarımızı beğenip paylaşarak katılabilirsiniz. Bol şans!"},
            {text: "Input: 200 TL üzerinde alışveriş yaptığım halde kargo ücreti alındı."},
            {text: "Output: Yaşadığınız aksaklık için özür dileriz. Sipariş numaranızı bizimle paylaşırsanız konuyu kontrol edebiliriz."},
            {text: "Input: Online alışverişlerde indirim kodunu kullandım ve gayet memnun kaldım."},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Mesaj"},
            {text: "Output: Cevap"},
            {text: "Input: Kampanya sayesinde evimin tüm temizlik malzemelerini çok uygun fiyata aldım, çok memnun kaldım."},
            {text: "Output: Mutlu olmanıza vesil olmak harika! Tekrar bekleriz."},
            {text: "Input: Anneler Günü kampanyasındaki ürünlerin stokları çok çabuk tükendi, daha fazla ürün ekleseniz keşke."},
            {text: "Output: Talebinizi not aldık, gelecek kampanyalarda dikkate alacağız."},
            {text: "Input: Babam için aldığım tıraş makinesinde güzel bir indirim yakaladım, teşekkürler Nova Market!"},
            {text: "Output: Babalar Günü'nü kutlarız! Keyifli günlerde kullanması dileğiyle."},
            {text: "Input: Aldığım valizin kampanyaya dahil olmadığını sonradan öğrendim, bu konuda daha dikkatli olmanızı rica ederim."},
            {text: "Output: Yaşadığınız olumsuzluk için özür dileriz. Kampanya detaylarını kontrol ederek size en kısa zamanda dönüş yapacağız."},
            {text: "Input: Geri dönüşüm programınıza hangi ürünleri verebilirim?"},
            {text: "Output: Detaylı bilgi için market.novamarket.net/geri-donusum adresini ziyaret edebilir veya müşteri hizmetlerimizi arayabilirsiniz."},
            {text: "Input: Müşteri sadakat programınız sayesinde kazandığım puanlarla bedava alışveriş yapmanın keyfini yaşıyorum."},
            {text: "Output: Programımızdan memnun kaldığınıza sevindik!"},
            {text: "Input: Haftalık tekliflerinizdeki indirimler çok düşük, daha cazip indirimler beklerdim."},
            {text: "Output: Geri bildiriminiz için teşekkürler, değerlendirmeye alacağız."},
            {text: "Input: Sosyal medya çekilişinizden hediye çeki kazandım, çok teşekkür ederim!"},
            {text: "Output: Tebrikler! Keyifli alışverişler dileriz."},
            {text: "Input: Ücretsiz kargo kampanyanız sayesinde alışverişlerimi daha avantajlı yapıyorum, teşekkürler."},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Online alışverişlerde indirim kodunu nasıl kullanabilirim?"},
            {text: "Output: İndirim kodunu, ödeme sayfasındaki \"İndirim Kodu\" alanına girmeniz yeterlidir."},
            {text: "Input: Kampanya kapsamında aldığım ürünün bir hafta sonra fiyatı daha da düştü."},
            {text: "Output: Kampanya dönemleri dışında uygulanan fiyat politikamız farklılık gösterebilir."},
            {text: "Input: Annem için aldığım hediyelerde kampanyanız sayesinde bütçemi korudum, teşekkürler."},
            {text: "Output: Annenizin Anneler Günü'nü kutlarız!"},
            {text: "Input: Babalar Günü kampanyanız ne zaman başlayacak?"},
            {text: "Output: Babalar Günü kampanyamız Haziran ayı içerisinde başlayacaktır. Web sitemizi ve sosyal medya hesaplarımızı takipte kalın!"},
            {text: "Input: Kampanyanız sayesinde tatil valizimi yeniledim, indirimler için teşekkürler!"},
            {text: "Output: Keyifli bir tatil geçirmenizi dileriz!"},
            {text: "Input: Eski telefonumu getirdiğimde değerinin çok altında bir indirim uygulandı."},
            {text: "Output: Geri dönüşüm programımız kapsamında uygulanan indirimler, ürünün marka ve modeline göre değişiklik göstermektedir."},
            {text: "Input: Müşteri sadakat programına nasıl üye olabilirim?"},
            {text: "Output: Müşteri kartı başvurusu için mağazalarımızdaki müşteri hizmetleri departmanına başvurabilirsiniz."},
            {text: "Input: Haftalık teklifleriniz sayesinde her hafta farklı bir ürünü indirimli alma fırsatı buluyorum, çok memnunum."},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Sosyal medya çekilişlerine katılıyorum ama hiç kazanamıyorum :("},
            {text: "Output: Çekilişlerimiz tamamen şansa dayalıdır, katılımınızı sürdürmenizi öneririz. Bol şans!"},
            {text: "Input: Ücretsiz kargo kampanyanız hangi illerde geçerli?"},
            {text: "Output: Ücretsiz kargo kampanyamız tüm Türkiye'de geçerlidir."},
            {text: "Input: Online alışverişlerde verdiğiniz indirimler sayesinde internetten alışveriş yapmak çok daha avantajlı hale geldi."},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Kampanya sayesinde bahar temizliğimi daha uygun fiyata tamamlayabildim."},
            {text: "Output: Evinizde baharın tadını çıkartmanız dileğiyle!"},
            {text: "Input: Anneler Günü kampanyanızda sadece belirli ürünlerde indirim olması hoşuma gitmedi."},
            {text: "Output: Geri bildiriminizi not aldık, gelecek kampanyalarımızda değerlendireceğiz."},
            {text: "Input: Babam için aldığım hediyeyi kampanyanız sayesinde çok uyguna aldım, teşekkürler Nova Market!"},
            {text: "Output: Babalar Günü'nü kutlarız!"},
            {text: "Input: Yaz tatili kampanyanız ne zaman bitecek?"},
            {text: "Output: Yaz tatili kampanyamız Temmuz ayı sonuna kadar devam edecektir."},
            {text: "Input: Geri dönüşüm kampanyanız sayesinde hem eski eşyamdan kurtuldum hem de yeni ürünümde indirim kazandım."},
            {text: "Output: Doğayı korumaya verdiğiniz destek için teşekkür ederiz!"},
            {text: "Input: Müşteri sadakat programında biriken puanların kullanım süresi çok kısa."},
            {text: "Output: Geri bildiriminizi not aldık, değerlendirmeye alacağız."},
            {text: "Input: Haftalık tekliflerinizi nereden takip edebilirim?"},
            {text: "Output: Haftalık tekliflerimizi web sitemizden, mobil uygulamamızdan ve sosyal medya hesaplarımızdan takip edebilirsiniz."},
            {text: "Input: Nova Market'in sosyal medya hesaplarını takip ettiğim için bir çekilişten hediye çeki kazandım, çok sevindim!"},
            {text: "Output: Tebrikler! Keyifli alışverişler dileriz."},
            {text: "Input: Ücretsiz kargo için belirlediğiniz minimum alışveriş tutarı çok yüksek."},
            {text: "Output: Geri bildiriminizi not aldık, değerlendirmeye alacağız."},
            {text: "Input: Online alışverişlerde indirim kodu kullanmadan indirimden yararlanabilir miyim?"},
            {text: "Output: Online alışverişlerde indirimden yararlanmak için indirim kodu kullanmanız gerekmektedir."},
            {text: "Input: Kampanya sayesinde bahçe mobilyalarımı yeniledim, çok şık oldular."},
            {text: "Output: Bahçenizde keyifli günler geçirmenizi dileriz!"},
            {text: "Input: Anneler Günü kampanyasında ürün çeşitliliği daha fazla olabilirdi."},
            {text: "Output: Geri bildiriminizi not aldık, gelecek kampanyalarımızda daha dikkatli olacağız."},
            {text: "Input: Babam için aldığım hediyeyi kampanyanız sayesinde yarı fiyatına aldım, çok teşekkür ederim Nova Market!"},
            {text: "Output: Babalar Günü'nü kutlarız!"},
            {text: "Input: Yaz tatili kampanyanız kapsamında hangi ürünlerde indirim var?"},
            {text: "Output: Kampanyamız kapsamında çadır, kamp malzemesi, valiz, güneş gözlüğü, havlu ve terlik gibi birçok üründe indirim bulunmaktadır."},
            {text: "Input: Geri dönüşüm kampanyanız sayesinde hem çevreye katkıda bulundum hem de indirim kazandım, tebrik ederim!"},
            {text: "Output: Doğayı korumaya verdiğiniz destek için teşekkür ederiz!"},
            {text: "Input: Müşteri sadakat programında biriken puanlarımı nasıl kullanabilirim?"},
            {text: "Output: Biriken puanlarınızı mağazalarımızda veya online alışverişlerinizde ödeme sırasında kullanabilirsiniz."},
            {text: "Input: Haftalık teklifleriniz sayesinde temel gıda ürünlerini çok uygun fiyatlara alabiliyorum."},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Sosyal medya çekilişlerinizin sonuçlarını açıklamıyorsunuz."},
            {text: "Output: Çekiliş sonuçlarımızı her zaman sosyal medya hesaplarımızdan duyuruyoruz. Takipte kalmanızı öneririz."},
            {text: "Input: Ücretsiz kargo kampanyanız sayesinde alışverişlerimi eve teslim alıyorum, çok pratik!"},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Online alışverişlerde indirim kodu kullanırken nelere dikkat etmeliyim?"},
            {text: "Output: İndirim kodlarının büyük/küçük harf duyarlılığına sahip olabileceğini ve belirli bir kullanım süresi olduğunu unutmayın."},
            {text: "Input: Kampanya sayesinde bahçe mobilyalarımı yeniledim, çok şık oldular!"},
            {text: "Output: Bahçenizde keyifli sohbetler geçirmeniz dileğiyle!"},
            {text: "Input: Anneler Günü kampanyasında hediye seçeneği daha fazla olabilirdi."},
            {text: "Output: Geri bildiriminiz için teşekkür ederiz, gelecek kampanyalarımızda değerlendireceğiz."},
            {text: "Input: Babam için aldığım cep telefonunu kampanyanız sayesinde çok uygun fiyata aldım, çok teşekkür ederim Nova Market!"},
            {text: "Output: Babalar Günü'nü kutlarız, yeni telefonunun hayırlı olmasını dileriz!"},
            {text: "Input: Yaz tatili kampanyanız online alışverişlerde de geçerli mi?"},
            {text: "Output: Evet, yaz tatili kampanyamız hem mağazalarımızda hem de online mağazamızda geçerlidir."},
            {text: "Input: Geri dönüşüm kampanyanız sayesinde hem eski buzdolabımdan kurtuldum hem de yeni aldığım buzdolabında indirim kazandım, harika bir uygulama!"},
            {text: "Output: Doğayı korumaya verdiğiniz destek için teşekkür eder, yeni buzdolabınızın hayırlı olmasını dileriz!"},
            {text: "Input: Müşteri sadakat programında puan biriktirmek için ne kadarlık alışveriş yapmam gerekiyor?"},
            {text: "Output: Müşteri sadakat programımızda her 100 TL'lik alışverişinize 1 puan kazanırsınız."},
            {text: "Input: Haftalık teklifleriniz sayesinde haftalık market alışverişimi çok daha ekonomik yapıyorum."},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Sosyal medya çekilişlerinizde katılım şartları çok karmaşık."},
            {text: "Output: Katılım şartlarını basitleştirmek için elimizden geleni yapacağız."},
            {text: "Input: Ücretsiz kargo kampanyanız sayesinde ağır market alışverişlerimi bile kolaylıkla taşıyabiliyorum."},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Online alışverişlerde indirim kodu kullanmak zorunlu mu?"},
            {text: "Output: Hayır, indirim kodu kullanmak zorunlu değildir. Ancak indirim kodları kullanarak alışverişlerinizde ekstra avantajlar sağlayabilirsiniz."},
            {text: "Input: Kampanya ürünlerinin stokları yetersizdi, istediğim bazı ürünleri bulamadım."},
            {text: "Output: Yoğun ilgiden dolayı bazı ürünlerimizde stok sıkıntısı yaşanmış olabilir, özür dileriz."},
            {text: "Input: Annem için aldığım mutfak robotunu kampanyanız sayesinde çok uygun fiyata aldım, annem çok mutlu oldu!"},
            {text: "Output: Annenizin Anneler Günü'nü kutlarız, yeni mutfak robotunun hayırlı olmasını dileriz!"},
            {text: "Input: Babalar Günü kampanyanız kapsamında hangi ödeme seçenekleri geçerli?"},
            {text: "Output: Babalar Günü kampanyamızda tüm ödeme seçeneklerimiz geçerlidir."},
            {text: "Input: Kampanyanız sayesinde tatil bavulumuzu uygun fiyatlara yeniledik, teşekkür ederiz!"},
            {text: "Output: Keyifli bir tatil geçirmenizi dileriz!"},
            {text: "Input: Geri dönüşüm kampanyası hakkında mağaza çalışanlarınız yeterli bilgiye sahip değil."},
            {text: "Output: Çalışanlarımızı bilgilendirmek için gerekli aksiyonları alacağız."},
            {text: "Input: Müşteri sadakat programınız sayesinde her alışverişimden puan kazanıyorum ve bu puanları sonraki alışverişlerimde kullanabiliyorum, çok avantajlı!"},
            {text: "Output: Programımızdan memnun kaldığınıza sevindik!"},
            {text: "Input: Haftalık teklifler ne zaman yenileniyor?"},
            {text: "Output: Haftalık tekliflerimiz her Pazartesi günü yenilenmektedir."},
            {text: "Input: Nova Market'in sosyal medya çekilişinden kazandığım hediye çeki ile harika bir alışveriş yaptım, teşekkürler!"},
            {text: "Output: Tebrikler, keyifli alışverişler dileriz!"},
            {text: "Input: Ücretsiz kargo seçeneği ile verdiğim siparişim çok geç geldi."},
            {text: "Output: Yaşadığınız gecikmeden dolayı özür dileriz, sipariş numaranızı paylaşırsanız konuyu inceleyebiliriz."},
            {text: "Input: Online alışverişlerde uyguladığınız indirimler sayesinde internetten alışveriş yapmak çok daha keyifli hale geldi!"},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Bahar temizliği kampanyanız sayesinde evimi baştan aşağıya yeniledim!"},
            {text: "Output: Evinizde baharın tadını çıkarmanız dileğiyle!"},
            {text: "Input: Anneler Günü kampanyasındaki indirimler yeterince cazip değildi."},
            {text: "Output: Geri bildiriminizi not aldık, gelecek kampanyalarımızda değerlendireceğiz."},
            {text: "Input: Babam için aldığım yeni televizyonu kampanyanız sayesinde çok uygun fiyata aldım, babam çok sevindi!"},
            {text: "Output: Babalar Günü'nü kutlar, yeni televizyonunuzun hayırlı olmasını dileriz!"},
            {text: "Input: Yaz tatili kampanyanızda ücretsiz kargo seçeneği de var mı?"},
            {text: "Output: Evet, 200 TL ve üzeri alışverişlerinizde ücretsiz kargo seçeneğimizden yararlanabilirsiniz."},
            {text: "Input: Geri dönüşüm kampanyanız sayesinde hem eski çamaşır makinemden kurtuldum hem de yeni aldığım çamaşır makinemde indirim kazandım, süper bir uygulama!"},
            {text: "Output: Doğayı korumaya verdiğiniz destek için teşekkür ederiz, yeni çamaşır makinenizin hayırlı olmasını dileriz!"},
            {text: "Input: Müşteri sadakat programına üye olmak için herhangi bir ücret ödemem gerekiyor mu?"},
            {text: "Output: Hayır, müşteri sadakat programına üye olmak tamamen ücretsizdir."},
            {text: "Input: Haftalık teklifleriniz sayesinde her hafta farklı bir ürünü indirimli alma fırsatı yakalıyorum, çok memnunum!"},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Sosyal medya çekilişlerinizi daha sık düzenleseniz keşke."},
            {text: "Output: Çekilişlerimizi belirli aralıklarla düzenlemeye çalışıyoruz, sosyal medya hesaplarımızı takipte kalın!"},
            {text: "Input: Ücretsiz kargo kampanyanız sayesinde market alışverişlerimi çok daha rahat yapıyorum."},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Online alışverişlerde hangi ödeme yöntemlerini kullanabilirim?"},
            {text: "Output: Online alışverişlerinizde kredi kartı, banka kartı ve kapıda ödeme seçeneklerini kullanabilirsiniz."},
            {text: "Input: Kampanya süresi çok kısaydı, uzatmanız mümkün mü?"},
            {text: "Output: Maalesef kampanya süremiz sona ermiştir, ancak yeni kampanyalarımızı takipte kalın!"},
            {text: "Input: Annem için aldığım hediyeleri kampanyanız sayesinde uygun fiyatlara aldım, annem çok sevindi!"},
            {text: "Output: Annenizin Anneler Günü'nü kutlarız!"},
            {text: "Input: Babalar Günü kampanyanızda hangi ürünlerde indirim var?"},
            {text: "Output: Babalar Günü kampanyamızda elektronik, giyim, spor, oto ve hobi gibi birçok kategoride yüzlerce üründe indirim bulunmaktadır."},
            {text: "Input: Kampanyanız sayesinde tatil valizimizi çok uygun fiyata aldık, teşekkür ederiz Nova Market!"},
            {text: "Output: Keyifli bir tatil geçirmenizi dileriz!"},
            {text: "Input: Geri dönüşüm kampanyanız sayesinde hem eski telefonumu değerlendirdim hem de yeni telefonumu indirimli aldım, harika bir uygulama!"},
            {text: "Output: Doğayı korumaya verdiğiniz destek için teşekkür eder, yeni telefonunuzun hayırlı olmasını dileriz!"},
            {text: "Input: Müşteri sadakat programında biriken puanlarımın son kullanma tarihi var mı?"},
            {text: "Output: Evet, biriken puanlarınızın 1 yıl sonrasında son kullanma tarihi dolacaktır."},
            {text: "Input: Haftalık teklifleriniz sayesinde temel ihtiyaçlarımı çok daha uygun fiyatlara alabiliyorum."},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Sosyal medya çekilişlerinizin kazananları gerçek kişiler mi?"},
            {text: "Output: Evet, çekiliş kazananlarımız tamamen gerçek kişilerdir ve kazananlarımızı sosyal medya hesaplarımızdan duyuruyoruz."},
            {text: "Input: Ücretsiz kargo kampanyanız sayesinde market alışverişimi evimden çıkmadan yapabiliyorum."},
            {text: "Output: Keyifli alışverişler dileriz!"},
            {text: "Input: Online alışverişlerde iade işlemleri nasıl yapılıyor?"},
            {text: "Output: Online alışverişlerinizde iade işlemleri hakkında detaylı bilgiye web sitemizden ulaşabilirsiniz."},
            {text: "Input: Elbiselerinizi yıkarken hangi programı kullanmalıyım?"},
            {text: "Output: Ürünlerimizin yıkama talimatları etiketlerinde belirtilmiştir. Genellikle hassas programda yıkamayı öneriyoruz."},
            {text: "Input: XS beden bir elbise ne kadar sürede kargoya verilir?"},
            {text: "Output: Tüm bedenler stoklarımızda mevcuttur. Siparişiniz ödeme onaylandıktan sonra 2 iş günü içinde kargoya verilir."},
            {text: "Input: İade etmek istediğim elbiseyi nasıl gönderebilirim?"},
            {text: "Output: İade etmek istediğiniz ürünü market.novamarket.net/iade-ve-degisim adresindeki talimatlara göre gönderebilirsiniz."},
            {text: "Input: Pantolon bedenleri dar mı kalıp olarak?"},
            {text: "Output: Pantolonlarımız standart kalıptır, beden tablomuzu kontrol ederek size uygun bedeni bulabilirsiniz."},
            {text: "Input: Bu sezon hangi renkler moda?"},
            {text: "Output: Bu sezon pastel tonlar, canlı renkler ve klasik siyah beyaz kombinleri moda."},
            {text: "Input: Kumaş içeriği hakkında bilgi verebilir misiniz?"},
            {text: "Output: Ürünlerimizin detay sayfasında kumaş içeriği bilgisi yer almaktadır."},
            {text: "Input: Aldığım eteğin ütü gerektiriyor mu?"},
            {text: "Output: Ürünlerimizin ütü talimatları etiketlerinde belirtilmiştir."},
            {text: "Input: Kombin önerisi alabilir miyim?"},
            {text: "Output: Stil danışmanlarımız size yardımcı olmaktan mutluluk duyar. Bizimle iletişime geçmek için market.novamarket.net/iletisim adresini ziyaret edebilirsiniz."},
            {text: "Input: Ürünlerinizde hangi markalar var?"},
            {text: "Output: Çeşitli markaları bünyemizde barındırıyoruz. Markalarımızı görmek için market.novamarket.net/markalar adresini ziyaret edebilirsiniz."},
            {text: "Input: Büyük beden seçenekleriniz mevcut mu?"},
            {text: "Output: Evet, geniş bir beden aralığında ürünler sunuyoruz."},
            {text: "Input: Beğendiğim ürün tekrar stoklara girecek mi?"},
            {text: "Output: Stoklarımızla ilgili güncel bilgiyi web sitemizden takip edebilirsiniz. Dilerseniz size ürün stoğa girdiğinde bilgilendirme maili gönderebiliriz."},
            {text: "Input: Hangi ödeme seçenekleri mevcut?"},
            {text: "Output: Kredi kartı, banka kartı, kapıda ödeme ve havale gibi çeşitli ödeme seçeneklerimiz mevcuttur."},
            {text: "Input: Kargo ücreti ne kadar?"},
            {text: "Output: Kargo ücreti sipariş tutarınıza ve teslimat adresinize göre değişiklik göstermektedir."},
            {text: "Input: Teslimat süresi ne kadar?"},
            {text: "Output: Teslimat süresi siparişinizin onaylanmasından sonra 2-5 iş günü arasındadır."},
            {text: "Input: Ürünlerin kalıpları nasıl?"},
            {text: "Output: Ürünlerimizin kalıpları genellikle standarttır ancak ürün detay sayfasında daha detaylı bilgi bulabilirsiniz."},
            {text: "Input: Beğendiğim bluz hangi renk seçeneklerine sahip?"},
            {text: "Output: Ürünlerimizin renk seçeneklerini ürün detay sayfasında bulabilirsiniz."},
            {text: "Input: İndirim ve kampanyalarınızdan nasıl haberdar olabilirim?"},
            {text: "Output: E-bültenimize abone olarak ve sosyal medya hesaplarımızı takip ederek güncel kampanyalarımızdan haberdar olabilirsiniz."},
            {text: "Input: Mağazalarınız nerede bulunuyor?"},
            {text: "Output: Mağazalarımızın adres bilgilerine web sitemizden ulaşabilirsiniz."},
            {text: "Input: Siparişimle ilgili bir sorun yaşadım, ne yapmalıyım?"},
            {text: "Output: Siparişinizle ilgili yaşadığınız sorunu çözmek için market.novamarket.net/iletisim adresinden bize ulaşabilirsiniz."},
            {text: "Input: Ürünlerinizin garantisi var mı?"},
            {text: "Output: Ürünlerimizin garanti süreleri ve koşulları markalara göre farklılık göstermektedir. Detaylı bilgi için ürün detay sayfasını kontrol edebilirsiniz."},
            {text: "Input: Gömlekleriniz hangi kumaşlardan üretiliyor?"},
            {text: "Output: Gömleklerimiz pamuk, keten, polyester gibi çeşitli kumaşlardan üretilmektedir. Detaylı bilgi için ürün detay sayfasını inceleyebilirsiniz."},
            {text: "Input: Siyah tişörtün hangi bedenleri mevcut?"},
            {text: "Output: Tüm ürünlerimizin beden seçeneklerini ürün detay sayfasında bulabilirsiniz."},
            {text: "Input: Ceketlerinizin kalıpları dar mı?"},
            {text: "Output: Ceketlerimiz standart kalıptır, beden tablomuzu kontrol ederek size uygun bedeni bulabilirsiniz."},
            {text: "Input: Kot pantolonlarda yıkama sonrası çekme yapar mı?"},
            {text: "Output: Kot pantolonlarımızda yıkama sonrası minimum düzeyde çekme olabilir."},
            {text: "Input: Spor giyimde hangi markaları satıyorsunuz?"},
            {text: "Output: Nike, Adidas, Puma gibi popüler spor giyim markalarını bünyemizde barındırıyoruz."},
            {text: "Input: Kravat ve papyon seçeneklerinizi nereden görebilirim?"},
            {text: "Output: Kravat ve papyon modellerimizi market.novamarket.net/erkek-giyim/aksesuar adresinde bulabilirsiniz."},
            {text: "Input: Yüzde yüz pamuklu kazaklarınız var mı?"},
            {text: "Output: Evet, yüzde yüz pamuklu kazak modellerimiz mevcuttur. Ürün filtreleme seçeneğinden kumaş türüne göre filtreleme yapabilirsiniz."},
            {text: "Input: Klasik ayakkabılarınızda hangi numaralar mevcut?"},
            {text: "Output: Ayakkabı numara seçeneklerimizi ürün detay sayfasında bulabilirsiniz."},
            {text: "Input: Ürünleri iade etmek için ne kadar sürem var?"},
            {text: "Output: İade etmek istediğiniz ürünleri teslim tarihinden itibaren 14 gün içinde iade edebilirsiniz."},
            {text: "Input: Online siparişimi mağazanızdan teslim alabilir miyim?"},
            {text: "Output: Evet, online siparişlerinizi mağazalarımızdan teslim alabilirsiniz. Siparişinizi oluştururken teslimat yöntemi olarak \"Mağazadan Teslim Al\" seçeneğini seçmeniz yeterlidir."},
            {text: "Input: Ürünlerinizin fiyatları neden diğer mağazalara göre daha yüksek?"},
            {text: "Output: Ürünlerimizin kalitesi ve markası göz önünde bulundurulduğunda fiyatlarımız oldukça rekabetçidir. Ayrıca dönemsel olarak indirimler ve kampanyalar düzenliyoruz."},
            {text: "Input: Siparişim ne zaman kargoya verilir?"},
            {text: "Output: Siparişiniz ödeme onaylandıktan sonra 2 iş günü içinde kargoya verilir."},
            {text: "Input: Kargo takibini nasıl yapabilirim?"},
            {text: "Output: Siparişiniz kargoya verildikten sonra size gönderilen takip numarası ile kargonuzun durumunu market.novamarket.net/siparis-takibi adresinden takip edebilirsiniz."},
            {text: "Input: Hediye paketi yapıyor musunuz?"},
            {text: "Output: Evet, hediye paketi hizmetimiz mevcuttur. Siparişinizi oluştururken \"Hediye Paketi\" seçeneğini işaretleyebilirsiniz."},
            {text: "Input: Ürünlerin bedenleri dar mı?"},
            {text: "Output: Ürünlerimiz standart kalıptır, ancak ürün detay sayfasında daha detaylı bilgi bulabilirsiniz."},
            {text: "Input: Siparişimi nasıl iptal edebilirim?"},
            {text: "Output: Siparişinizi iptal etmek için market.novamarket.net/iletisim adresinden müşteri hizmetlerimizle iletişime geçebilirsiniz."},
            {text: "Input: Ürünleriniz garantili mi?"},
            {text: "Output: Ürünlerimizin garanti süreleri ve koşulları markalara göre farklılık göstermektedir. Detaylı bilgi için ürün detay sayfasını kontrol edebilirsiniz."},
            {text: "Input: İndirimli ürünlerde iade hakkım var mı?"},
            {text: "Output: Evet, indirimli ürünlerde de iade hakkınız bulunmaktadır. Ancak bazı özel durumlar için iade koşulları farklılık gösterebilir."},
            {text: "Input: Mağazanızda terzi hizmeti veriyor musunuz?"},
            {text: "Output: Mağazalarımızda terzi hizmeti olup olmadığını market.novamarket.net/magaza-bul adresinden kontrol edebilirsiniz."},
            {text: "Input: Ürünleriniz hakkında detaylı bilgi alabilir miyim?"},
            {text: "Output: Ürünlerimiz hakkında detaylı bilgiye ürün detay sayfasından ulaşabilirsiniz. Ayrıca market.novamarket.net/iletisim adresinden müşteri hizmetlerimizle iletişime geçebilirsiniz."},
            {text: "Input: Bebek kıyafetleriniz hangi kumaşlardan üretiliyor?"},
            {text: "Output: Bebek kıyafetlerimiz çoğunlukla organik pamuktan üretiliyor, hassas ciltler için idealdir."},
            {text: "Input: 3 yaşındaki oğlum için hangi bedeni almalıyım?"},
            {text: "Output: Beden tablomuzu kullanarak çocuğunuz için en uygun bedeni bulabilirsiniz."},
            {text: "Input: Kız çocuk elbiseleri yıkanınca çekme yapar mı?"},
            {text: "Output: Ürünlerimizde yıkama sonrası minimum düzeyde çekme olabilir. Yıkama talimatlarını etiketten kontrol etmenizi öneririz."},
            {text: "Input: Montların su geçirmezlik özelliği var mı?"},
            {text: "Output: Bazı mont modellerimiz su geçirmez özelliğe sahiptir. Ürün detay sayfasında bu bilgiyi bulabilirsiniz."},
            {text: "Input: İade etmek istediğim ürünü nasıl gönderebilirim?"},
            {text: "Output: İade etmek istediğiniz ürünü Yurtiçi Kargo ile ücretsiz olarak gönderebilirsiniz. Detaylı bilgi için web sitemizi ziyaret edin."},
            {text: "Input: Hangi yaş grupları için kıyafetler satıyorsunuz?"},
            {text: "Output: 0-16 yaş arası tüm çocuk yaş grupları için kıyafetlerimiz mevcuttur."},
            {text: "Input: Organik pamuktan üretilmiş kıyafetlerinizi nasıl ayırt edebilirim?"},
            {text: "Output: Organik pamuktan üretilen ürünlerimizde \"Organik\" etiketi bulunmaktadır."},
            {text: "Input: Beğendiğim ürünün farklı renk seçenekleri var mı?"},
            {text: "Output: Ürünlerimizin renk seçeneklerini ürün detay sayfasında görüntüleyebilirsiniz."},
            {text: "Input: Ürünlerinizde kullanılan boyalar sağlığa zararlı mı?"},
            {text: "Output: Ürünlerimizde kullanılan tüm boyalar çocuk sağlığına uygun ve sertifikalıdır."},
            {text: "Input: Siparişim ne zaman teslim edilir?"},
            {text: "Output: Siparişiniz ortalama 3 iş günü içinde adresinize teslim edilir."},
            {text: "Input: Kız çocuk abiye modelleri mağazanızda mevcut mu?"},
            {text: "Output: Evet, özel günler için şık kız çocuk abiye modellerimizi mağazalarımızda bulabilirsiniz."},
            {text: "Input: Erkek çocuk takım elbise fiyatları hakkında bilgi alabilir miyim?"},
            {text: "Output: Takım elbise fiyatlarımız modele ve bedenine göre değişiklik göstermektedir. Web sitemizden inceleyebilirsiniz."},
            {text: "Input: Ürünlerinizde hangi markalar bulunuyor?"},
            {text: "Output: Çeşitli yerli ve yabancı markaları bünyemizde barındırıyoruz. Marka listesine web sitemizden ulaşabilirsiniz."},
            {text: "Input: Bebek battaniyesi ve nevresim takımı fiyatları nelerdir?"},
            {text: "Output: Fiyatlarımıza web sitemizden veya mağazalarımızdan ulaşabilirsiniz."},
            {text: "Input: Siparişimi nasıl takip edebilirim?"},
            {text: "Output: Siparişinizi market.novamarket.net/siparis-takibi adresinden takip edebilirsiniz."},
            {text: "Input: Ürünleri mağazadan değişim yapabilir miyim?"},
            {text: "Output: Evet, online olarak aldığınız ürünleri mağazalarımızdan değiştirebilirsiniz."},
            {text: "Input: Kampanya ve indirimlerinizden nasıl haberdar olabilirim?"},
            {text: "Output: E-bültenimize abone olarak ve sosyal medya hesaplarımızı takip ederek güncel kampanyalarımızdan haberdar olabilirsiniz."},
            {text: "Input: Ürünlerin yıkama talimatları nelerdir?"},
            {text: "Output: Yıkama talimatları ürün etiketlerinde belirtilmiştir."},
            {text: "Input: Ürünlerinizde kanserojen madde bulunuyor mu?"},
            {text: "Output: Hayır, ürünlerimizde çocuk sağlığına zararlı hiçbir madde bulunmamaktadır."},
            {text: "Input: Kişisel verilerim güvende mi?"},
            {text: "Output: Kişisel verileriniz KVKK kapsamında korunmaktadır."},
            {text: "Input: Pamuklu çoraplarınız hangi renklerde var?"},
            {text: "Output: Pamuklu çoraplarımızda geniş bir renk seçeneği sunuyoruz. Web sitemizi inceleyebilirsiniz."},
            {text: "Input: Sütyen bedenimi nasıl doğru alabilirim?"},
            {text: "Output: Doğru sütyen bedeni bulmak için beden ölçü tablomuzu kullanabilir veya mağazalarımızda ücretsiz ölçüm yaptırabilirsiniz."},
            {text: "Input: İç çamaşırlarında hangi markalar var?"},
            {text: "Output: Penti, Kom, Ten gibi markaların ürünlerini bünyemizde barındırıyoruz."},
            {text: "Input: Külotlu çoraplar kaç den?"},
            {text: "Output: Farklı den seçeneklerine sahibiz. Ürün detay sayfasında bu bilgiyi bulabilirsiniz."},
            {text: "Input: Erkek boxer modelleriniz nelerdir?"},
            {text: "Output: Klasik, spor, slip gibi çeşitli boxer modellerimiz mevcuttur."},
            {text: "Input: Ürünlerinizde hangi kumaşlar kullanılıyor?"},
            {text: "Output: Pamuk, mikrofiber, saten, dantel gibi çeşitli kumaşlar kullanıyoruz. Ürün detay sayfasında kumaş bilgisine ulaşabilirsiniz."},
            {text: "Input: İade etmek istediğim iç çamaşırını nasıl gönderebilirim?"},
            {text: "Output: Hijyen açısından iç çamaşırı iadesi kabul edilmemektedir."},
            {text: "Input: Çoraplarda indirim var mı?"},
            {text: "Output: Dönemsel olarak çorap indirimleri yapıyoruz. Kampanyalarımızı takipte kalın."},
            {text: "Input: Büyük beden iç giyim seçenekleriniz mevcut mu?"},
            {text: "Output: Evet, geniş bir beden aralığında iç giyim seçenekleri sunuyoruz."},
            {text: "Input: Siparişim ne zaman kargoya verilir?"},
            {text: "Output: Siparişiniz ödeme onaylandıktan sonra 2 iş günü içinde kargoya verilir."},
            {text: "Input: Hangi kargo şirketi ile çalışıyorsunuz?"},
            {text: "Output: Yurtiçi Kargo ile çalışıyoruz."},
            {text: "Input: Ürünlerinizin kalitesi hakkında bilgi alabilir miyim?"},
            {text: "Output: Ürünlerimiz yüksek kalite standartlarında üretilmektedir."},
            {text: "Input: Siyah külotlu çorap kaç derecede yıkanır?"},
            {text: "Output: Ürünlerimizin yıkama talimatları etiketlerinde belirtilmiştir."},
            {text: "Input: Erkek çoraplarında hangi numaralar mevcut?"},
            {text: "Output: 39-46 numara aralığında erkek çorabı seçeneklerimiz mevcuttur."},
            {text: "Input: Sporcu sütyeni arıyorum, önerileriniz nelerdir?"},
            {text: "Output: Sporcu sütyeni modellerimizi market.novamarket.net/ic-giyim-ve-corap/sporcu-sutyeni adresinden inceleyebilirsiniz."},
            {text: "Input: Ürünlerin fiyatları neden diğer mağazalara göre daha pahalı?"},
            {text: "Output: Ürünlerimizin kalitesi ve markası göz önünde bulundurulduğunda fiyatlarımız oldukça rekabetçidir."},
            {text: "Input: İç giyimde hangi renkler moda?"},
            {text: "Output: Bu sezon iç giyimde pastel tonlar, siyah, beyaz ve kırmızı renkler trend."},
            {text: "Input: Mağazanızdan telefonla sipariş verebilir miyim?"},
            {text: "Output: Maalesef telefonla sipariş almamaktayız. Siparişlerinizi web sitemizden veya mağazalarımızdan verebilirsiniz."},
            {text: "Input: Kapıda ödeme seçeneği mevcut mu?"},
            {text: "Output: Evet, kapıda ödeme seçeneğimizle güvenli bir şekilde alışveriş yapabilirsiniz."},
            {text: "Input: İade etmek istediğim ürünü mağazadan teslim edebilir miyim?"},
            {text: "Output: Evet, online siparişlerinizi mağazalarımıza iade edebilirsiniz."},
            {text: "Input: Güneş gözlüklerinizde UV koruması var mı?"},
            {text: "Output: Evet, tüm güneş gözlüklerimiz %100 UV koruması sağlar."},
            {text: "Input: Şapka bedenleri nasıl?"},
            {text: "Output: Şapka bedenlerimizi ürün detay sayfasında bulabilirsiniz. Genellikle standart bedenlerdir ancak bazı modellerde ayarlanabilir özellikler olabilir."},
            {text: "Input: Kolye ve küpeleriniz hangi malzemelerden üretiliyor?"},
            {text: "Output: Kolye ve küpelerimiz genellikle gümüş, altın kaplama, çelik ve bijuteri malzemelerden üretilmektedir. Detaylı bilgi için ürün açıklamalarını inceleyebilirsiniz."},
            {text: "Input: Atkı ve bere takımlarınızda hangi renk seçenekleri var?"},
            {text: "Output: Geniş bir renk seçeneği sunuyoruz. Web sitemizden tüm renkleri inceleyebilirsiniz."},
            {text: "Input: Saç aksesuarlarınızda hangi modeller mevcut?"},
            {text: "Output: Toka, bandana, saç bandı gibi çeşitli saç aksesuarı modellerimiz mevcuttur."},
            {text: "Input: Beğendiğim eldivenin farklı bedenleri var mı?"},
            {text: "Output: Beden seçeneklerini ürün detay sayfasında bulabilirsiniz."},
            {text: "Input: Güneş gözlüğü camı kırıldı, değiştirebilir miyim?"},
            {text: "Output: Maalesef sadece ürünün tamamını iade alabiliyoruz. Ancak garanti kapsamında ise yardımcı olabiliriz."},
            {text: "Input: Hangi markaların aksesuarlarını satıyorsunuz?"},
            {text: "Output: Fossil, Guess, X&O gibi birçok ünlü markanın ürünlerini bünyemizde barındırıyoruz."},
            {text: "Input: Erkek şapka modelleriniz nelerdir?"},
            {text: "Output: Kasket, fötr şapka, bere gibi çeşitli erkek şapka modellerimiz mevcuttur."},
            {text: "Input: Siparişimi teslim aldığımda ödeme yapabilir miyim?"},
            {text: "Output: Evet, kapıda ödeme seçeneğimizle siparişinizi teslim aldığınızda ödeme yapabilirsiniz."},
            {text: "Input: Ürünleri mağazadan iade edebilir miyim?"},
            {text: "Output: Evet, online olarak aldığınız ürünleri mağazalarımıza iade edebilirsiniz."},
            {text: "Input: İndirim ve kampanyalarınızdan nasıl haberdar olabilirim?"},
            {text: "Output: E-bültenimize abone olarak ve sosyal medya hesaplarımızı takip ederek güncel kampanyalarımızdan haberdar olabilirsiniz."},
            {text: "Input: Kişiye özel tasarım aksesuar yapıyor musunuz?"},
            {text: "Output: Maalesef kişiye özel tasarım hizmetlerimiz bulunmamaktadır."},
            {text: "Input: Ürünlerinizin garantisi var mı?"},
            {text: "Output: Ürünlerimizin garanti süreleri ve koşulları markalara göre farklılık göstermektedir. Detaylı bilgi için ürün detay sayfasını kontrol edebilirsiniz."},
            {text: "Input: Aldığım fular lekelendi, nasıl temizleyebilirim?"},
            {text: "Output: Temizleme talimatları ürün etiketinde belirtilmiştir."},
            {text: "Input: Ürünlerinizin fiyatları neden diğer mağazalara göre daha pahalı?"},
            {text: "Output: Ürünlerimizin kalitesi ve markası göz önünde bulundurulduğunda fiyatlarımız oldukça rekabetçidir."},
            {text: "Input: Aksesuar siparişimde kargo ücreti ne kadar?"},
            {text: "Output: Kargo ücreti sipariş tutarınıza ve teslimat adresinize göre değişiklik göstermektedir."},
            {text: "Input: Mağazanızda takı tamir hizmeti veriyor musunuz?"},
            {text: "Output: Maalesef takı tamir hizmeti vermiyoruz."},
            {text: "Input: Hediye paketi yapıyor musunuz?"},
            {text: "Output: Evet, hediye paketi hizmetimiz mevcuttur. Siparişinizi oluştururken \"Hediye Paketi\" seçeneğini işaretleyebilirsiniz."},
            {text: "Input: Ürünleriniz hakkında daha fazla bilgi alabilir miyim?"},
            {text: "Output: Ürünlerimiz hakkında daha fazla bilgi için market.novamarket.net/iletisim adresinden müşteri hizmetlerimizle iletişime geçebilirsiniz."},
            {text: "Input: Spor ayakkabılarda hangi markaları bulabilirim?"},
            {text: "Output: Nike, Adidas, Puma, Skechers gibi birçok popüler spor ayakkabı markasını bulabilirsiniz."},
            {text: "Input: Ayakkabı numaramı nasıl doğru bir şekilde belirleyebilirim?"},
            {text: "Output: Web sitemizde yer alan \"Ayakkabı Ölçü Tablosu\"nu kullanarak ayak numaranızı ölçebilirsiniz."},
            {text: "Input: Siyah deri botun 38 numarası mevcut mu?"},
            {text: "Output: Ürünlerimizin beden ve renk seçenekleri stok durumuna göre değişiklik gösterebilir. Web sitemizden kontrol edebilirsiniz."},
            {text: "Input: Topuklu ayakkabılarınız rahat mı?"},
            {text: "Output: Ayakkabılarımızda konfor ön planda tutularak tasarlanmıştır. Ancak rahatlık algısı kişiden kişiye değişiklik gösterebilir."},
            {text: "Input: Erkek klasik ayakkabı modelleriniz nelerdir?"},
            {text: "Output: Oxford, Loafer, Derby gibi klasik erkek ayakkabı modellerini bulabilirsiniz."},
            {text: "Input: Çocuk ayakkabılarında hangi yaş gruplarına hizmet veriyorsunuz?"},
            {text: "Output: 0-16 yaş arası tüm çocuk yaş grupları için ayakkabı modellerimiz mevcuttur."},
            {text: "Input: Aldığım ayakkabıyı iade etmek istiyorum, nasıl bir yol izlemeliyim?"},
            {text: "Output: İade koşullarımız ve iade süreci ile ilgili detaylı bilgiye web sitemizden ulaşabilirsiniz."},
            {text: "Input: Ayakkabılar su geçirmez mi?"},
            {text: "Output: Bazı ayakkabı modellerimiz su geçirmez özelliğe sahiptir. Ürün detay sayfasında bu bilgiyi bulabilirsiniz."},
            {text: "Input: Hangi ödeme yöntemlerini kullanabilirim?"},
            {text: "Output: Kredi kartı, banka kartı, kapıda ödeme ve havale gibi çeşitli ödeme seçeneklerini kullanabilirsiniz."},
            {text: "Input: Siparişim ne kadar sürede teslim edilir?"},
            {text: "Output: Siparişleriniz ortalama 2-5 iş günü içerisinde adresinize teslim edilir."},
            {text: "Input: Ayakkabılarımı nasıl temizlemeliyim?"},
            {text: "Output: Temizleme talimatları ürünün iç etiketinde yer almaktadır."},
            {text: "Input: Mağazanızda ayakkabı tamir hizmeti veriyor musunuz?"},
            {text: "Output: Maalesef mağazalarımızda ayakkabı tamir hizmeti vermiyoruz."},
            {text: "Input: Hediye paketi seçeneğiniz var mı?"},
            {text: "Output: Evet, hediye paketi seçeneğimiz mevcuttur. Siparişinizi oluştururken \"Hediye Paketi\" seçeneğini işaretleyebilirsiniz."},
            {text: "Input: Ürünleriniz garantili mi?"},
            {text: "Output: Ürünlerimizin garanti süreleri ve koşulları markalara göre farklılık göstermektedir. Detaylı bilgi için ürün detay sayfasını kontrol edebilirsiniz."},
            {text: "Input: Ayakkabıların kalıpları dar mı?"},
            {text: "Output: Ayakkabı kalıpları marka ve modele göre değişiklik gösterebilir. Detaylı bilgi için ürün açıklamalarını inceleyebilirsiniz."},
            {text: "Input: Siparişimi nasıl takip edebilirim?"},
            {text: "Output: Siparişinizi market.novamarket.net/siparis-takibi adresinden takip edebilirsiniz."},
            {text: "Input: Ayakkabıları mağazadan değiştirebilir miyim?"},
            {text: "Output: Evet, online olarak aldığınız ürünleri mağazalarımızdan değiştirebilirsiniz."},
            {text: "Input: İndirim ve kampanyalarınızdan nasıl haberdar olabilirim?"},
            {text: "Output: E-bültenimize abone olarak ve sosyal medya hesaplarımızı takip ederek güncel kampanyalarımızdan haberdar olabilirsiniz."},
            {text: "Input: Kişiye özel tasarım ayakkabı yapıyor musunuz?"},
            {text: "Output: Maalesef kişiye özel tasarım hizmetlerimiz bulunmamaktadır."},
            {text: "Input: Ayakkabılar hakkında daha fazla bilgi alabilir miyim?"},
            {text: "Output: Ayakkabılar hakkında daha fazla bilgi için market.novamarket.net/iletisim adresinden müşteri hizmetlerimizle iletişime geçebilirsiniz."},
    
        ],
      },
      
    ],
  });

  const result = await chatSession.sendMessage(userInput);
  const response = result.response;
  return response.text();
}

app.get('/', (req, res) => {
  res.sendFile(__dirname + '/index.html');
});
app.get('/loader.gif', (req, res) => {
  res.sendFile(__dirname + '/loader.gif');
});
app.post('/chat', async (req, res) => {
  try {
    const userInput = req.body?.userInput;
    console.log('incoming /chat req', userInput)
    if (!userInput) {
      return res.status(400).json({ error: 'Invalid request body' });
    }

    const response = await runChat(userInput);
    res.json({ response });
  } catch (error) {
    console.error('Error in chat endpoint:', error);
    res.status(500).json({ error: 'Internal Server Error' });
  }
});

app.listen(port, () => {
  console.log(`Server listening on port ${port}`);
});